
export const icons: Record<string, { uri: string }> = {
    back: { uri: 'material/icons/back.png' },
    heart_icon: { uri: 'material/icons/heart_icon.png' },
    bride_and_groom: { uri: 'material/icons/bride_and_groom.png' },
    cake: { uri: 'material/icons/cake.png' },
    clock: { uri: 'material/icons/clock.png' },
    dance: { uri: 'material/icons/dance.png' },
    farewell: { uri: 'material/icons/farewell.png' },
    open_link_icon:{uri:'material/icons/open_link_icon.png'},
    folk_dish_spoon: { uri: 'material/icons/folk_dish_spoon.png' },
    group_love: { uri: 'material/icons/group_love.png' },
    group: { uri: 'material/icons/group.png' },
    heart_logo_icon: { uri: 'material/icons/heart_icon.png' },
    love_talks: { uri: 'material/icons/love_talks.png' },
    nikkah_diary: { uri: 'material/icons/nikkah_diary.png' },
    party_bumper: { uri: 'material/icons/party_bumper.png' },
    splash_screen_logo: { uri: 'material/icons/Splash_screen_logo.png' },
    fb_icon: { uri: 'material/icons/fb.png' },
    black_cross_icon: { uri: 'material/icons/black_cross_icon.png' },
    google_icon: { uri: 'material/icons/google.png' },
    email_icon: { uri: 'material/icons/email.png' },
    full_name_person: { uri: 'material/icons/f_name_person.png' },
    profile_no_image: { uri: 'material/icons/person_icon.png' },
    ai_logo: { uri: 'material/icons/ai_logo.png' },
    image_icon: { uri: 'material/icons/image_icon.png' },
    icon_heart: { uri: 'material/icons/LikeHeart.png' },
    video_icon: { uri: 'material/icons/video_icon.png' },
    home_icon: { uri: 'material/icons/SimpleHome.png' },
    user_icon: { uri: 'material/icons/user_icon.png' },
    gift_icon: { uri: 'material/icons/SimpleGifts.png' },
    users_icon: { uri: 'material/icons/SimpleUsers.png' },
    sending_icon: { uri: 'material/icons/SendingIcon.png' },
    star_mark: { uri: 'material/icons/StarMark.png' },
    modal_sign: { uri: 'material/icons/ModalSign.png' },
    action_sheet_icon: { uri: 'material/icons/ActionSheetIcon.png' },
    modal_desc_icon: { uri: 'material/icons/ModalDescIcon.png' },
    edit_icon: { uri: 'material/icons/edit_icon.png' },
    delete_icon: { uri: 'material/icons/delete_icon.png' },
    modal_dollar_icon: { uri: 'material/icons/ModalDollarIcon.png' },
    refresh_icon: { uri: 'material/icons/refresh_icon.png' },
    report_sign_icon: { uri: 'material/icons/report_sign_icon.png' },
    DescriptionIcon1: { uri: 'material/icons/Description1Icon.png' },
    DescriptionIcon2: { uri: 'material/icons/Description2Icon.png' },
    Blocked_Icon: { uri: 'material/icons/Blocked_Icon.png' },
    Locked_Icon: { uri: 'material/icons/Lock_Icon.png' },
    Question_Icon: { uri: 'material/icons/Question_Icon.png' },
    Delete_Icon: { uri: 'material/icons/Delete_Icon_Final.png' },
    Message_Icon: { uri: 'material/icons/Message_Icon.png' },
    Exclamatory_Icon: { uri: 'material/icons/Exclamatory_Icon.png' },
    Cross_Icon: { uri: 'material/icons/Menu_Cross_Icon.png' },
    Clock_Icon: { uri: 'material/icons/Clock_Icon.png' },
    add_post: { uri: 'material/icons/add_post.png' },
    add_filled_icon: { uri: 'material/icons/add_filled_icon.png' },
    left_arrow_icon:{uri:'material/icons/left_arrow_icon.png'},
    right_arrow_icon:{uri:'material/icons/right_arrow_icon.png'},
    round_filled_x_icon:{uri:'material/icons/round_filled_x.png'},
    exclamatoryFORhelpandsupport_Icon: { uri: 'material/icons/EXCLAMATORY.png' },
    helpaandSupport_Icon_QuestionMark: { uri: 'material/icons/HelpAndSupport_Icon.png' },
    whatsapp: { uri: 'material/icons/whatsapp.png' },
    instagram: { uri: 'material/icons/instagram.png' },
    sharelink: { uri: 'material/icons/sharelink.png' },
    double_Heart:{uri:'material/icons/SimpleHeart.png'},
    menu_Icon:{uri:'material/icons/Menu_Icon.png'},
    ourstoryheader_Icon:{uri:'material/icons/OurStoryHeader_Icon.png'},
    PostFieldMeni_Icon:{uri:'material/icons/PostFieldMenu_Icon.png'},
    SpotLightDelete_Icon:{uri:'material/icons/SpotlightDelete_Icon.png'},
    vertical_three_dots:{uri:'material/icons/vertical_three_dots.png'},
    feed_bottom_bar_icon:{uri:'material/icons/feed_bottom_bar.png'},
    gift_bottom_bar_icon:{uri:'material/icons/gift_bottom_bar.png'},
    ourStory_bottom_bar_icon:{uri:'material/icons/loveStory_bottom_bar.png'},
    arrowBack_Icon:{uri:'material/icons/arrowBackIcon.png'},
//   back: { uri: "material/icons/back.png" },
//   heart_icon: { uri: "material/icons/heart_icon.png" },
//   bride_and_groom: { uri: "material/icons/bride_and_groom.png" },
//   cake: { uri: "material/icons/cake.png" },
//   clock: { uri: "material/icons/clock.png" },
//   dance: { uri: "material/icons/dance.png" },
//   farewell: { uri: "material/icons/farewell.png" },
//   folk_dish_spoon: { uri: "material/icons/folk_dish_spoon.png" },
//   group_love: { uri: "material/icons/group_love.png" },
//   group: { uri: "material/icons/group.png" },
//   heart_logo_icon: { uri: "material/icons/heart_icon.png" },
//   love_talks: { uri: "material/icons/love_talks.png" },
//   nikkah_diary: { uri: "material/icons/nikkah_diary.png" },
//   party_bumper: { uri: "material/icons/party_bumper.png" },
//   splash_screen_logo: { uri: "material/icons/Splash_screen_logo.png" },
//   fb_icon: { uri: "material/icons/fb.png" },
//   google_icon: { uri: "material/icons/google.png" },
//   email_icon: { uri: "material/icons/email.png" },
//   full_name_person: { uri: "material/icons/f_name_person.png" },
//   profile_no_image: { uri: "material/icons/person_icon.png" },
//   ai_logo: { uri: "material/icons/ai_logo.png" },
//   image_icon: { uri: "material/icons/image_icon.png" },
//   icon_heart: { uri: "material/icons/LikeHeart.png" },
//   video_icon: { uri: "material/icons/video_icon.png" },
//   home_icon: { uri: "material/icons/SimpleHome.png" },
//   user_icon: { uri: "material/icons/user_icon.png" },
//   gift_icon: { uri: "material/icons/SimpleGifts.png" },
//   users_icon: { uri: "material/icons/SimpleUsers.png" },
//   sending_icon: { uri: "material/icons/SendingIcon.png" },
//   star_mark: { uri: "material/icons/StarMark.png" },
//   modal_sign: { uri: "material/icons/ModalSign.png" },
//   action_sheet_icon: { uri: "material/icons/ActionSheetIcon.png" },
//   modal_desc_icon: { uri: "material/icons/ModalDescIcon.png" },
//   edit_icon: { uri: "material/icons/edit_icon.png" },
//   delete_icon: { uri: "material/icons/delete_icon.png" },
//   modal_dollar_icon: { uri: "material/icons/ModalDollarIcon.png" },
//   refresh_icon: { uri: "material/icons/refresh_icon.png" },
//   report_sign_icon: { uri: "material/icons/report_sign_icon.png" },
//   DescriptionIcon1: { uri: "material/icons/Description1Icon.png" },
//   DescriptionIcon2: { uri: "material/icons/Description2Icon.png" },
//   Blocked_Icon: { uri: "material/icons/Blocked_Icon.png" },
//   Locked_Icon: { uri: "material/icons/Lock_Icon.png" },
//   Question_Icon: { uri: "material/icons/Question_Icon.png" },
//   Delete_Icon: { uri: "material/icons/Delete_Icon_Final.png" },
//   Message_Icon: { uri: "material/icons/Message_Icon.png" },
//   Exclamatory_Icon: { uri: "material/icons/Exclamatory_Icon.png" },
//   Cross_Icon: { uri: "material/icons/Menu_Cross_Icon.png" },
//   Clock_Icon: { uri: "material/icons/Clock_Icon.png" },
//   add_post: { uri: "material/icons/add_post.png" },
//   add_filled_icon: { uri: "material/icons/add_filled_icon.png" },
//   left_arrow_icon: { uri: "material/icons/left_arrow_icon.png" },
//   right_arrow_icon: { uri: "material/icons/right_arrow_icon.png" },
//   round_filled_x_icon: { uri: "material/icons/round_filled_x.png" },
//   exclamatoryFORhelpandsupport_Icon: { uri: "material/icons/EXCLAMATORY.png" },
//   helpaandSupport_Icon_QuestionMark: {
//     uri: "material/icons/HelpAndSupport_Icon.png",
//   },
//   whatsapp: { uri: "material/icons/whatsapp.png" },
//   instagram: { uri: "material/icons/instagram.png" },
//   sharelink: { uri: "material/icons/sharelink.png" },
//   double_Heart: { uri: "material/icons/SimpleHeart.png" },
//   menu_Icon: { uri: "material/icons/Menu_Icon.png" },
//   ourstoryheader_Icon: { uri: "material/icons/OurStoryHeader_Icon.png" },
//   PostFieldMeni_Icon: { uri: "material/icons/PostFieldMenu_Icon.png" },
//   SpotLightDelete_Icon: { uri: "material/icons/SpotlightDelete_Icon.png" },
  Drop_Down_Icon_Down: { uri: "material/icons/DropDown_Icon.png" },
  SignOut_Icon: { uri: "material/icons/SignOut_Icon.png" },
  check_Mark_Icon: { uri: "material/icons/check_Mark_Icon.png" },
  uncheck_Mark_Icon: { uri: "material/icons/uncheck_Mark_Icon.png" },
  FAQS_Icon:{uri:'material/icons/faqs_ICON.png'},
  TickQuestion_Icon:{uri:'material/icons/TickIconQuestion.png'},
  CrossQuestion_Icon:{uri:'material/icons/DeleteIconQuestion.png'},
  TrivaiQuizModal:{uri:'material/icons/TriviaModalIcon.png'},
  SimpleoptionQuiz_Icon:{uri:'material/icons/SImpleQuiziCON.png'}
  
};
