export const images=
{
    couple_photo:{uri:'material/Images/couple.jpg'},
    // celebrate_together:require('./celebrate_together.png'),
    // download_n_share:require('./download_n_share.png'),
    // contribute_effortlessly:require('./contribute_effortlessly.png'),
    // discover_n_engage:require('./discover_n_engage.png'),
    // profile_image:require('./profile_image.jpg'),
    // cash:require('./cash.png'),
    // honey_moon_trip:require('./honey_moon_trip.png'),
    // payment_processed:require('./payment_processed.png'),
    // circle_dollar:require('./circle_dollar.png'),
    // house_image:require('./house_image.png'),
    // payment_failure:require('./payment_failed.png'),
    // payment_success:require('./payment_success.png'),
    // receipt_distribution_line:require('./receipt_distribution_line.png'),    couple_photo: { uri: 'Resources/Images/couple.jpg' },
    celebrate_together: { uri: 'material/Images/celebrate_together.png' },
    download_n_share: { uri: 'material/Images/download_n_share.png' },
    contribute_effortlessly: { uri: 'material/Images/contribute_effortlessly.png' },
    discover_n_engage: { uri: 'material/Images/discover_n_engage.png' },
    profile_image: { uri: 'material/Images/profile_image.jpg' },
    cash: { uri: 'material/Images/cash.png' },
    honey_moon_trip: { uri: 'material/Images/honey_moon_trip.png' },
    payment_processed: { uri: 'material/Images/payment_processed.png' },
    circle_dollar: { uri: 'material/Images/circle_dollar.png' },
    house_image: { uri: 'material/Images/house_image.png' },
    payment_failure: { uri: 'material/Images/payment_failed.png' },
    payment_success: { uri: 'material/Images/payment_success.png' },
    receipt_distribution_line: { uri: 'material/Images/receipt_distribution_line.png' },
    QuestionCard_Background:{uri:'material/Images/Question_Background.jpeg'}
}